# Generated by Django 5.2.6 on 2026-02-04 07:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0005_userprofile_group_userprofile_identity_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job_Positions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='員工職稱')),
            ],
            options={
                'verbose_name_plural': '員工職稱',
            },
        ),
        migrations.AddField(
            model_name='userprofile',
            name='jobp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='register.job_positions', verbose_name='員工職稱'),
        ),
    ]
