# Generated by Django 5.2.6 on 2026-02-04 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0006_job_positions_userprofile_jobp'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='地址'),
        ),
    ]
