# Generated by Django 5.2.6 on 2026-02-05 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0009_userprofile_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='identity',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True, verbose_name='身份證字號'),
        ),
    ]
