# Generated by Django 5.2.6 on 2026-02-11 07:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0011_userprofile_salary'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Calendar_Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='事件標題')),
                ('description', models.TextField(blank=True, null=True, verbose_name='事件描述')),
                ('start_time', models.DateTimeField(help_text='0-23', verbose_name='開始時間')),
                ('end_time', models.DateTimeField(help_text='0-23', verbose_name='結束時間')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendars', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '員工行事曆',
                'verbose_name_plural': '員工行事曆',
            },
        ),
    ]
