# Generated by Django 5.0.1 on 2024-02-02 06:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('office', models.CharField(max_length=255)),
                ('ext', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('share', models.CharField(max_length=255)),
                ('Job_title', models.CharField(max_length=10)),
                ('PC_ID', models.CharField(max_length=255)),
                ('ip', models.CharField(max_length=255)),
                ('PC', models.CharField(max_length=255)),
                ('LCD', models.CharField(max_length=255)),
                ('MacAddress', models.CharField(max_length=255)),
                ('dey', models.DateTimeField(default=datetime.datetime(2024, 2, 2, 6, 42, 6, 103179, tzinfo=datetime.timezone.utc))),
            ],
        ),
    ]
