# Generated by Django 5.0.1 on 2024-02-05 07:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userMaterial', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermaterial',
            name='Job_title',
            field=models.CharField(max_length=10, verbose_name='職稱'),
        ),
        migrations.AlterField(
            model_name='usermaterial',
            name='LCD',
            field=models.CharField(max_length=255, verbose_name='螢幕型號'),
        ),
        migrations.AlterField(
            model_name='usermaterial',
            name='PC',
            field=models.CharField(max_length=255, verbose_name='電腦型號'),
        ),
        migrations.AlterField(
            model_name='usermaterial',
            name='PC_ID',
            field=models.CharField(max_length=255, verbose_name='電腦名稱'),
        ),
        migrations.AlterField(
            model_name='usermaterial',
            name='dey',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 5, 7, 1, 51, 636064, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='usermaterial',
            name='ext',
            field=models.IntegerField(verbose_name='分機'),
        ),
        migrations.AlterField(
            model_name='usermaterial',
            name='ip',
            field=models.CharField(max_length=255, verbose_name='IP'),
        ),
        migrations.AlterField(
            model_name='usermaterial',
            name='name',
            field=models.CharField(max_length=10, verbose_name='使用者'),
        ),
        migrations.AlterField(
            model_name='usermaterial',
            name='office',
            field=models.CharField(max_length=255, verbose_name='辦公室'),
        ),
        migrations.AlterField(
            model_name='usermaterial',
            name='share',
            field=models.CharField(max_length=5, verbose_name='股別'),
        ),
    ]
