# Generated by Django 5.2.6 on 2025-09-05 01:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userMaterial', '0002_alter_usermaterial_job_title_alter_usermaterial_lcd_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usermaterial',
            options={'verbose_name_plural': '使用者'},
        ),
        migrations.AlterField(
            model_name='usermaterial',
            name='dey',
            field=models.DateTimeField(default=datetime.datetime(2025, 9, 5, 1, 56, 43, 863501, tzinfo=datetime.timezone.utc)),
        ),
    ]
