# Generated by Django 5.2.6 on 2025-12-18 09:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userMaterial', '0003_alter_usermaterial_options_alter_usermaterial_dey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermaterial',
            name='dey',
            field=models.DateTimeField(default=datetime.datetime(2025, 12, 18, 9, 57, 0, 594578, tzinfo=datetime.timezone.utc)),
        ),
    ]
