# Generated by Django 5.2.6 on 2025-12-19 05:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userMaterial', '0004_alter_usermaterial_dey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermaterial',
            name='dey',
            field=models.DateTimeField(default=datetime.datetime(2025, 12, 19, 5, 20, 19, 378981, tzinfo=datetime.timezone.utc)),
        ),
    ]
