# Generated by Django 5.2.6 on 2025-12-22 07:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userMaterial', '0005_alter_usermaterial_dey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermaterial',
            name='dey',
            field=models.DateTimeField(default=datetime.datetime(2025, 12, 22, 7, 29, 45, 742363, tzinfo=datetime.timezone.utc)),
        ),
    ]
