# Generated by Django 5.2.6 on 2026-01-29 08:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userMaterial', '0006_alter_usermaterial_dey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermaterial',
            name='dey',
            field=models.DateTimeField(default=datetime.datetime(2026, 1, 29, 8, 54, 0, 931753, tzinfo=datetime.timezone.utc)),
        ),
    ]
