# Generated by Django 5.2.6 on 2026-02-04 07:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userMaterial', '0007_alter_usermaterial_dey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermaterial',
            name='dey',
            field=models.DateTimeField(default=datetime.datetime(2026, 2, 4, 7, 18, 39, 316650, tzinfo=datetime.timezone.utc)),
        ),
    ]
