# Generated by Django 5.2.6 on 2026-02-04 07:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userMaterial', '0008_alter_usermaterial_dey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermaterial',
            name='dey',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
