# Generated by Django 5.2.6 on 2026-01-23 03:50

import ckeditor.fields
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('title_announcement', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='titleannouncement',
            options={'verbose_name': '公告', 'verbose_name_plural': '公告'},
        ),
        migrations.AlterField(
            model_name='titleannouncement',
            name='announcement',
            field=ckeditor.fields.RichTextField(verbose_name='公告內容'),
        ),
        migrations.AlterField(
            model_name='titleannouncement',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='發布時間'),
        ),
    ]
